# Generated by Django 2.2 on 2019-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ManyToManyField(related_name='Events', to='eventFinderApp.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='Categories', to='eventFinderApp.Category'),
        ),
    ]
