# Generated by Django 2.2 on 2019-09-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_auto_20190918_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time and date'),
        ),
    ]
