# Generated by Django 2.2 on 2019-09-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0004_auto_20190906_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='eventFinderApp.Category'),
        ),
    ]
