# Generated by Django 2.2 on 2019-09-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0004_auto_20190918_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hosting_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
