# Generated by Django 2.2 on 2019-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0005_auto_20190918_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.CharField(default='description', max_length=600),
        ),
    ]
