# Generated by Django 2.2 on 2019-09-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0009_auto_20190926_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_description',
        ),
    ]
