# Generated by Django 2.2 on 2019-09-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0011_event_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default='media/download.jpg', null=True, upload_to='event_images/%Y/%m/%D/'),
        ),
    ]
