# Generated by Django 2.2 on 2019-09-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0013_auto_20190930_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
