# Generated by Django 2.2 on 2019-09-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0014_auto_20190930_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default='Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(max_length=600),
        ),
    ]
